
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';import vm from 'node:vm';import {discover,filterPapers,doiKey,normalizeWork,relevant,uniqueWorks,crossrefURL,titleKey,looksLikeDoi,searchCrossrefURL,searchWorks,sortByFocus} from '../src/literature.js';
test('DOI normalization and deduplication',()=>{assert.equal(doiKey('https://doi.org/10.ABC/XYZ'),'10.abc/xyz');assert.equal(uniqueWorks([{doi:'10.ABC/x'},{doi:'10.abc/X'}]).length,1);assert.equal(uniqueWorks([{doi:'10.a/1',label:'Same Title'},{doi:'10.b/2',label:'Same Title'}]).length,1);assert.ok(titleKey('Hello, World!'))});
test('catalysis discovery drops protein/drug ligand papers and keeps catalytic ligand work',()=>{
 const keep=normalizeWork({title:['Bayesian Optimization for Accelerated Ligand Selection in Atroposelective Negishi Coupling'],DOI:'10.keep/1'});
 const drop=normalizeWork({title:['Transferable Collective Variable to accelerate Protein-Ligand Unbinding via Machine Learning'],DOI:'10.drop/1'});
 const drug=normalizeWork({title:['Machine Learning in Ligand-based Drug Design'],DOI:'10.drop/2'});
 assert.equal(relevant(keep,'catalysis'),true);
 assert.equal(relevant(drop,'catalysis'),false);
 assert.equal(relevant(drug,'catalysis'),false);
});
test('discovery excludes unrelated and future work, tolerates partial failure',async()=>{let i=0;const data={DOI:'10.test/1',title:['Machine learning for catalytic reactions'],published:{'date-parts':[[2026,9,1]]}};const result=await discover({now:new Date('2026-09-06'),fetcher:async()=>{if(i++===0)throw Error();return {ok:true,json:async()=>({message:{items:[data,{...data,DOI:'10.test/future',published:{'date-parts':[[2026,10,1]]}},{...data,DOI:'10.test/other',title:['Machine learning for EFL teachers']}]}})}}});assert.equal(result.failed,1);assert.equal(result.papers.length,1)});
test('all-provider failure is surfaced',async()=>{await assert.rejects(discover({fetcher:async()=>{throw Error('offline')}}),/unavailable/)});
test('Milo filtering requires Anat Milo, not other Milo authors',()=>{assert.equal(relevant(normalizeWork({author:[{given:'Anat',family:'Milo'}]}),'milo'),true);assert.equal(relevant(normalizeWork({author:[{given:'Peter',family:'Milo'}]}),'milo'),false)});
test('feed query uses date bounds and relevance before local date sort',()=>{const u=new URL(crossrefURL('ligand machine learning','catalysis',30,new Date('2026-09-06')));assert.equal(u.searchParams.get('filter'),'from-pub-date:2026-08-07,until-pub-date:2026-09-06');assert.equal(u.searchParams.get('sort'),'relevance')});
test('DOI or title search hits Crossref and can return a work',async()=>{
 assert.equal(looksLikeDoi('https://doi.org/10.1021/jacs.1c09718'),true);
 assert.equal(looksLikeDoi('ligand GNN hydroformylation'),false);
 const doiURL=searchCrossrefURL('https://doi.org/10.1021/jacs.1c09718');
 assert.ok(doiURL.endsWith('/works/10.1021%2Fjacs.1c09718'));
 const qURL=new URL(searchCrossrefURL('hydroformylation GNN',3650,new Date('2026-09-06')));
 assert.equal(qURL.searchParams.get('query'),'hydroformylation GNN');
 const found=await searchWorks({q:'10.1234/add.1',fetcher:async()=>({ok:true,json:async()=>({message:{DOI:'10.1234/add.1',title:['A catalytic ML paper'],author:[{given:'A',family:'B'}]}})})});
 assert.equal(found.doi,true);assert.equal(found.papers.length,1);assert.equal(found.papers[0].doi,'10.1234/add.1');
});
test('corpus integrity and preserved atlas',async()=>{const g=JSON.parse(await readFile('dist/graph.json','utf8'));const ps=g.nodes.filter(p=>p.type==='paper');assert.equal(ps.length,83);assert.equal(new Set(ps.filter(p=>p.doi).map(p=>doiKey(p.doi))).size,82);assert.ok(ps.filter(p=>p.published_date).length>=81);assert.ok(ps.every(p=>p.summary&&p.summary.length>24&&p.ask_next&&p.brief&&p.use_for&&p.stack_layer));
assert.ok(ps.filter(p=>p.figure?.src).length>=30);
assert.ok(g.insights?.stats?.papers===83);
assert.ok(ps.some(p=>p.id==='paper_harper_sterimol_2012'));
assert.ok(ps.some(p=>p.id==='paper_aqme_2023'));
assert.ok(ps.some(p=>p.id==='paper_lustosa_milo_2022'));
assert.ok(ps.some(p=>p.id==='paper_molli_2024'));
assert.ok(ps.some(p=>p.id==='paper_sambvca_pockets_2019'));
assert.ok(ps.some(p=>p.id==='paper_sigman_accounts_2016'));
assert.equal(ps.find(p=>p.id==='paper_edbo_2021').stack_layer,'Experiment selection');
assert.equal(ps.find(p=>p.id==='paper_edboplus_2022').stack_layer,'Experiment selection');
assert.equal(ps.find(p=>p.id==='paper_ni_edbo_2024').stack_layer,'Experiment selection');
assert.notEqual(ps.find(p=>p.id==='paper_edbo_2021').doi,ps.find(p=>p.id==='paper_ni_edbo_2024').doi);
assert.equal(ps.find(p=>p.id==='paper_racerts_2026').stack_layer,'TS ensembles');
assert.equal(ps.find(p=>p.id==='paper_crest_2024').stack_layer,'Ground-state conformers');
assert.equal(ps.find(p=>p.id==='paper_harper_sterimol_2012').descriptytor_rank,1);
assert.equal(ps.find(p=>p.id==='paper_autoqchem_2022').descriptytor_role,'contrast-pool');
assert.equal(filterPapers(ps,{focus:'descriptytor'}).length,21);
assert.equal(sortByFocus(filterPapers(ps,{focus:'descriptytor'}),'descriptytor')[0].id,'paper_harper_sterimol_2012');
assert.ok(g.stories?.chemist_frames);
assert.ok(g.stories?.descriptytor);
assert.ok(g.stories.descriptytor.ids.includes('paper_molli_2024'));
assert.ok(g.stories?.computational_stack);
assert.ok(g.insights.gaps.length>=3);
assert.ok(g.insights.heatmap.length>20);assert.ok(filterPapers(ps,{focus:'milo'}).length>=8);assert.ok(filterPapers(ps,{focus:'stack'}).length>=8);assert.ok(filterPapers(ps,{representation:'Learned 3D / TS GNN'}).length>=3);const ids=new Set(g.nodes.map(n=>n.id));for(const e of g.edges){assert.ok(ids.has(e.source));assert.ok(ids.has(e.target))}const h=await readFile('dist/atlas.html','utf8');const js=await readFile('dist/atlas.js','utf8');const css=await readFile('dist/style.css','utf8');assert.ok(!h.includes('https://unpkg.com'));assert.ok(js.includes('autoRotate = false'));assert.ok(css.includes('#side{display:grid'));assert.ok(h.includes('id="chemistry"'));assert.ok(h.includes('Color: representation'));assert.ok(h.includes('id="stack"'));assert.ok(h.includes('atlas.js'));assert.ok(h.includes('id="figbox"'));assert.ok(h.includes('id="showFigs"'));assert.ok(js.includes('data-fig'));assert.ok(js.includes('figImage'));assert.ok(js.includes('packRect'));assert.ok(js.includes('s.ids'));assert.ok(!h.includes('ALL_NODES='));new vm.Script(js)});
test('reading UI: search, filter, details, save, read, compare and discovery failure',async()=>{
 const html=await readFile('src/index.html','utf8'),graph=JSON.parse(await readFile('dist/graph.json','utf8'));
 const dom=new JSDOM(html,{url:'https://atlas.test/',runScripts:'outside-only'}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.discover=async()=>{throw Error('offline')};w.filterPapers=filterPapers;w.sortByFocus=sortByFocus;w.doiKey=doiKey;
 w.searchWorks=async({q})=>({papers:[{id:'doi:10.1234/add.1',doi:'10.1234/add.1',label:'Machine learning for a new catalytic ligand',full_title:'Machine learning for a new catalytic ligand',candidate:true,derived_authors:['Test Author'],journal:'JACS',year:2025,published_date:'2025-06-01',url:'https://doi.org/10.1234/add.1',derived_methods:[],derived_topics:[],groups:[]}],fetched_at:'2026-09-06T00:00:00Z',query:q,doi:true});
 w.fetch=async path=>({ok:true,json:async()=>String(path).includes('graph.json')?graph:{papers:[],fetched_at:'2026-09-06T00:00:00Z'}});
 w.eval((await readFile('src/app.js','utf8')).replace(/^\s*import .*?;\s*/,''));
 await new Promise(r=>setTimeout(r,20));
 const q=s=>w.document.querySelector(s);assert.equal(w.document.querySelectorAll('.paper').length,83);
 q('[data-view="inspect"]').click();
 assert.equal(w.document.querySelectorAll('table.inspect tbody tr').length,83);
 assert.ok(q('#results').textContent.includes('racerTS')||q('table.inspect').textContent.includes('EDBO'));
 q('th[data-sort="n"] button').click();
 q('tr[data-detail]').click();assert.equal(q('#detail').open,true);assert.ok(q('#detail-body').textContent.includes('Stack layer'));
 q('#close-detail').click();q('[data-view="library"]').click();
 assert.equal(w.document.querySelectorAll('.paper').length,83);
 assert.ok(w.document.querySelectorAll('.fig-card').length>=10);
 q('.fig-card').click();assert.equal(q('#figbox').open,true);q('#close-fig').click();
 q('#focus').value='milo';q('#focus').dispatchEvent(new w.Event('change'));assert.ok(w.document.querySelectorAll('.paper').length>=4);
 q('[data-detail]').click();assert.equal(q('#detail').open,true);assert.ok(q('#detail-body').textContent.includes('Summary'));assert.ok(q('#detail-body').textContent.includes('Ask next'));
 q('#close-detail').click();
 q('#focus').value='descriptytor';q('#focus').dispatchEvent(new w.Event('change'));
 assert.equal(w.document.querySelectorAll('.paper').length,21);
 assert.ok(q('.paper').textContent.includes('Sterimol')||q('.paper').textContent.toLowerCase().includes('sterimol'));
 assert.ok(q('.prompt')?.textContent.includes('DescriPyTor')||q('#source-note').textContent.includes('DescriPyTor'));
 q('[data-view="inspect"]').click();
 assert.equal(w.document.querySelectorAll('table.inspect tbody tr').length,21);
 assert.ok(q('table.inspect').classList.contains('descriptytor'));
 assert.ok(q('#results').textContent.includes('vs DescriPyTor'));
 assert.ok(q('table.inspect tbody tr').textContent.includes('#'));
 q('#close-detail')?.click();q('[data-view="library"]').click();
 q('#focus').value='milo';q('#focus').dispatchEvent(new w.Event('change'));
 q('[data-view="board"]').click();assert.ok(q('.heat'));assert.ok(q('#results').textContent.includes('Open cells'));assert.ok(q('#results').textContent.includes('Stack layer'));
 q('[data-view="library"]').click();
 const id=q('[data-detail]').dataset.detail;q('[data-detail]').click();assert.equal(q('#detail').open,true);assert.ok(q('#detail-body').textContent.includes('Validation'));
 q('#detail-body [data-save]').click();assert.equal(q('#saved-count').textContent,'1');assert.ok(w.localStorage.getItem('cml:saved').includes(id));
 q('#detail-body [data-read]').click();assert.ok(w.localStorage.getItem('cml:read').includes(id));
 q('#detail-body [data-compare]').click();q('#close-detail').click();q('[data-view="compare"]').click();assert.ok(q('#comparison table').textContent.includes('Validation'));
 q('[data-view="latest"]').click();await new Promise(r=>setTimeout(r,20));assert.ok(q('#feed-status').textContent.includes('snapshot'));assert.equal(q('#refresh').disabled,false);
 q('#find').value='10.1234/add.1';q('#find-go').click();await new Promise(r=>setTimeout(r,20));
 assert.ok(q('[data-add]'));q('[data-add]').click();assert.ok(w.localStorage.getItem('cml:added').includes('10.1234/add.1'));
 q('#focus').value='';q('#focus').dispatchEvent(new w.Event('change'));q('[data-view="library"]').click();
 assert.ok([...w.document.querySelectorAll('.paper')].some(el=>el.textContent.includes('new catalytic ligand')));
 dom.window.close();
});

