
import {mkdir,readFile,writeFile,cp,copyFile} from 'node:fs/promises';
import {enrichGraph} from '../src/enrich.js';
await mkdir('dist/vendor',{recursive:true});
await cp('src','dist',{recursive:true});await cp('public','dist',{recursive:true});
const source=JSON.parse(await readFile('original/graph_catalysis_v7.json','utf8'));
const metadata=JSON.parse(await readFile('public/metadata.json','utf8'));
const authors=JSON.parse(await readFile('public/authors.json','utf8'));
const graph=enrichGraph(source,{metadata,authors});
await writeFile('dist/graph.json',JSON.stringify(graph));
let html=await readFile('original/catalysis_ml_atlas_v7.html','utf8');
html=html.replace(/const ALL_NODES=[\s\S]*?;const byId/,'const ALL_NODES='+JSON.stringify(graph.nodes)+',META_LINKS='+JSON.stringify(graph.edges)+',PAPER_LINKS='+JSON.stringify(graph.paper_similarity_edges)+',STORIES='+JSON.stringify(graph.stories)+';const byId');
html=html.replace('https://unpkg.com/three@0.160.0/build/three.min.js','vendor/three.min.js').replace('https://unpkg.com/3d-force-graph','vendor/3d-force-graph.min.js').replace('https://unpkg.com/three-spritetext','vendor/three-spritetext.min.js');
html=html.replace('<html>','<html lang="en">').replace('<div id="top">','<div id="top"><a href="./" class="paperLink">← Reading room</a><details id="graphControls"><summary>Graph controls & filters</summary>');
html=html.replace('<div class="row" id="storybar"></div>','<div class="row" id="storybar"></div></details>');
html=html.replace('<select id="colorby"><option value="paradigm" selected>Color: paradigm</option><option value="group">Color: PI / group</option><option value="year">Color: year</option><option value="type">Color: node type</option></select>',
 '<select id="colorby"><option value="paradigm" selected>Color: paradigm</option><option value="representation">Color: representation</option><option value="group">Color: PI / group</option><option value="year">Color: year</option><option value="type">Color: node type</option></select>');
html=html.replace('<select id="layout"><option value="free" selected>Layout: network</option><option value="year">Layout: timeline</option><option value="paradigm">Layout: paradigms</option><option value="group">Layout: PI / group</option></select>',
 '<select id="layout"><option value="free" selected>Layout: network</option><option value="year">Layout: timeline</option><option value="paradigm">Layout: paradigms</option><option value="representation">Layout: representation</option><option value="group">Layout: PI / group</option></select>');
html=html.replace('<select id="year"><option value="all">All years</option>',
 '<select id="chemistry"><option value="all">All chemistry</option></select><select id="representation"><option value="all">All representations</option></select><select id="year"><option value="all">All years</option>');
html=html.replace('const groupColors={','const representationColors={"Reusable ligand library":"#f0b45b","Physical / chemist descriptors":"#78a9ff","Conformer / ensemble descriptors":"#85d66f","Catalyst-state / mechanistic":"#69d1b2","Learned 3D / TS GNN":"#d88cff","Pretrained learned representation":"#c2a3ff","MLIP / physics acceleration":"#51c5dd","Dataset / experimental loop":"#ff5fa2","Overview / mixed":"#9aa7b8"};const groupColors={');
html=html.replace('"Hong":"#ff9d78","Other":"#9aa7b8"}','"Hong":"#ff9d78","Coley":"#9ad0ff","Duarte":"#7fd0b5","Cernak":"#e0a36b","Rajaraman":"#c9a6ff","Nova":"#7fb3d8","Glorius":"#f0c27a","Schreiner":"#8fd0a8","Woodward":"#f2a0b6","Alegre-Requena":"#9bb7e8","Other":"#9aa7b8"}');
html=html.replace('if(mode==="paradigm")return paradigmColors[n.paradigm]||"#9aa7b8";',
 'if(mode==="paradigm")return paradigmColors[n.paradigm]||"#9aa7b8";if(mode==="representation")return representationColors[n.representation_class]||"#9aa7b8";');
html=html.replace('let cmap=mode==="paradigm"?paradigmColors:mode==="group"?groupColors:mode==="year"?yearColors:typeColors;',
 'let cmap=mode==="paradigm"?paradigmColors:mode==="representation"?representationColors:mode==="group"?groupColors:mode==="year"?yearColors:typeColors;');
html=html.replace('if(s.keywords){const text=JSON.stringify(p).toLowerCase();if(!s.keywords.some(k=>text.includes(k)))return false}return true}',
 'if(s.representations&&!s.representations.includes(p.representation_class))return false;if(s.keywords){const text=JSON.stringify(p).toLowerCase();if(!s.keywords.some(k=>text.includes(k)))return false}return true}');
html=html.replace('if(hideReviews&&["review","perspective","viewpoint"].includes((n.paper_type||"").toLowerCase()))return false;if(!storyMatch(n))return false;return true}',
 'if(hideReviews&&["review","perspective","viewpoint"].includes((n.paper_type||"").toLowerCase()))return false;if(document.getElementById("chemistry").value!=="all"&&n.chemistry_class!==document.getElementById("chemistry").value)return false;if(document.getElementById("representation").value!=="all"&&n.representation_class!==document.getElementById("representation").value)return false;if(!storyMatch(n))return false;return true}');
html=html.replace('else if(mode==="paradigm"){',
 'else if(mode==="representation"){const cats=Object.keys(representationColors),ci=Object.fromEntries(cats.map((x,i)=>[x,i]));currentData.nodes.forEach(n=>{if(n.type==="paper"){const a=2*Math.PI*(ci[n.representation_class]||0)/cats.length,r=150;n.fx=r*Math.cos(a)+((hash(n.id)%100)/100-.5)*45;n.fy=r*Math.sin(a)+((hash(n.id+"y")%100)/100-.5)*45;n.fz=((hash(n.id+"z")%1000)/1000-.5)*90}});}else if(mode==="paradigm"){');
html=html.replace('if(n.chemistry)h+=`<div class="card"><h3>Chemistry</h3><div class="small">${esc(n.chemistry)}</div></div>`;',
 'if(n.chemistry_class)h+=`<div class="card"><h3>Chemistry class</h3><div class="small">${esc(n.chemistry_class)}</div></div>`;if(n.representation_class)h+=`<div class="card"><h3>Representation</h3><div class="small">${esc(n.representation_class)}</div></div>`;if(n.secondary_paradigms?.length)h+=`<div class="card"><h3>Also in</h3><div class="small">${esc(n.secondary_paradigms.join(" · "))}</div></div>`;if(n.chemistry)h+=`<div class="card"><h3>Chemistry</h3><div class="small">${esc(n.chemistry)}</div></div>`;');
html=html.replace('["Year",x=>x.year],["Journal",x=>x.journal],["Paradigm",x=>x.paradigm],["Group",x=>(x.groups||[]).join(", ")],["Chemistry",x=>x.chemistry],["Data",x=>x.data_regime],["Validation",x=>x.validation],["Methods",x=>(x.derived_methods||[]).join(", ")],["Why it matters",x=>x.why]',
 '["Year",x=>x.year],["Journal",x=>x.journal],["Paradigm",x=>x.paradigm],["Also in",x=>(x.secondary_paradigms||[]).join(", ")],["Representation",x=>x.representation_class],["Group",x=>(x.groups||[]).join(", ")],["Chemistry class",x=>x.chemistry_class],["Chemistry",x=>x.chemistry],["Data size",x=>x.data_size_bin],["Data",x=>x.data_regime],["Validation type",x=>x.validation_type],["Validation",x=>x.validation],["Methods",x=>(x.derived_methods||[]).join(", ")],["Why it matters",x=>x.why]');
html=html.replace('["q","view","year","density"].forEach(id=>document.getElementById(id).addEventListener(id==="q"?"input":"change",()=>{clearSelection();buildData()}));',
 '["q","view","year","density","chemistry","representation"].forEach(id=>document.getElementById(id).addEventListener(id==="q"?"input":"change",()=>{clearSelection();buildData();persistAtlas()}));');
html=html.replace('</style>',`
html,body{overflow:auto}#app{min-height:100dvh;height:auto}#main{height:80dvh;min-height:580px}#graphwrap{overflow:hidden}#graphControls summary{cursor:pointer;padding:12px;font-size:16px}input,select,button{min-height:44px;font-size:14px}#q{font-size:16px;max-width:100%}.small,.muted{font-size:14px}.card h3{font-size:18px}.tag{font-size:12px}table{font-size:14px}.rowitem{min-height:44px}#side{display:grid}.paperLink{min-height:44px}#hud{max-width:calc(100% - 24px)}#legend{max-height:240px;overflow:auto;pointer-events:auto}
@media(max-width:950px){#main{height:auto;display:flex;flex-direction:column;min-height:0}#graphwrap{height:52dvh;min-height:320px;flex:none}#side{display:grid;min-height:50dvh;border-left:0;border-top:1px solid #283544}#panel{max-height:none;overflow:visible;padding:16px}#tabs{position:sticky;top:0;background:#070b12;z-index:4}#legend{display:none}#hud .hudbox{font-size:12px;max-width:200px}#compareBadge{bottom:72px}.row select{max-width:100%}.row input{min-width:0}#top{padding:10px}#graphControls:not([open])+.row{display:none}}
</style>`);
html=html.replace('Graph.cooldownTicks(80);','Graph.cooldownTicks(80);Graph.controls().autoRotate=false;');
const atlasHelpers=`function persistAtlas(){try{localStorage.setItem("cml:atlas",JSON.stringify({q:document.getElementById("q").value,view:document.getElementById("view").value,layout:document.getElementById("layout").value,colorby:document.getElementById("colorby").value,year:document.getElementById("year").value,chemistry:document.getElementById("chemistry").value,representation:document.getElementById("representation").value,density:document.getElementById("density").value,story:activeStory}))}catch{}}
function restoreAtlas(){try{const s=JSON.parse(localStorage.getItem("cml:atlas")||"null");if(!s)return;for(const [k,v] of Object.entries(s)){if(k==="story"){activeStory=v;document.querySelectorAll("[data-story]").forEach(x=>x.classList.toggle("active",x.dataset.story===activeStory));continue}const el=document.getElementById(k);if(el&&v!=null)el.value=v}}catch{}}
function fillAtlasFilters(){const chems=[...new Set(allPapers.map(p=>p.chemistry_class).filter(Boolean))].sort();const chem=document.getElementById("chemistry"),rep=document.getElementById("representation");for(const c of chems)chem.insertAdjacentHTML("beforeend","<option>"+c+"</option>");for(const r of ["Reusable ligand library","Physical / chemist descriptors","Conformer / ensemble descriptors","Catalyst-state / mechanistic","Learned 3D / TS GNN","Pretrained learned representation","MLIP / physics acceleration","Dataset / experimental loop","Overview / mixed"])if(allPapers.some(p=>p.representation_class===r))rep.insertAdjacentHTML("beforeend","<option>"+r+"</option>");}
function selectNode(id){if(window.innerWidth<=950)setTimeout(()=>document.getElementById("side").scrollIntoView({behavior:"smooth",block:"start"}),50);`;
html=html.replace('function selectNode(id){',atlasHelpers);
html=html.replace('buildData();renderOverview();','fillAtlasFilters();restoreAtlas();buildData();applyLayout(document.getElementById("layout").value,false);renderOverview();new ResizeObserver(()=>Graph.width(document.getElementById("graphwrap").clientWidth).height(document.getElementById("graphwrap").clientHeight)).observe(document.getElementById("graphwrap"));document.getElementById("graphControls").open=window.innerWidth>950;document.getElementById("graph").setAttribute("aria-label","Interactive 3D research graph. Paper list and details are available below.");');
await writeFile('dist/atlas.html',html);
for(const [src,dst] of [['three/build/three.min.js','three.min.js'],['3d-force-graph/dist/3d-force-graph.min.js','3d-force-graph.min.js'],['three-spritetext/dist/three-spritetext.min.js','three-spritetext.min.js']])await copyFile('node_modules/'+src,'dist/vendor/'+dst);
const cols=['id','year','published_date','label','full_title','doi','url','paradigm','secondary_paradigms','representation_class','chemistry_class','chemistry','data_size_bin','data_regime','validation_type','validation'];
await writeFile('dist/papers.csv',cols.join(',')+'\n'+graph.nodes.filter(p=>p.type==='paper').map(p=>cols.map(k=>'"'+String(Array.isArray(p[k])?p[k].join('; '):p[k]??'').replaceAll('"','""')+'"').join(',')).join('\n'));
await writeFile('dist/.nojekyll','');
const papers=graph.nodes.filter(p=>p.type==='paper');
console.log('Built',papers.length,'papers;',graph.nodes.length,'nodes; representations',new Set(papers.map(p=>p.representation_class)).size);
